@startuml
!theme mars
' hide the spot
' hide circle
' avoid problems with angled crows feet
skinparam linetype ortho
entity "DANHMUC" #Pink {
*MaDanhMuc : number <<generated>>
--
*TenDanhMuc : text
*AnhDanhMuc : image
}

entity "SANPHAM" #Implementation  {
*MaSanPham : number <<generated>> 
--
*MaDanhMuc : number <<FK>>
GiaTien: money
AnhSanPham: image
MoTaSanPham : text
}

entity "KHUYENMAI" #Orchid{
*MaKhuyenMai: number <<genrerated>>
--
*TieuDeKhuyenMai: text
*AnhKhuyenMai: image
ChiTietKhuyenMai: text
MaDanhMuc : number <<FK>>
}

entity "GIOHANG-HOADON" #Lavender {
*MaNguoiDung : number <<FK>>
*MaSanPham : number <<FK>>
SoLuongSanPham: number
TongTien: money
}


entity "KHACHHANG" #LightYellow {
*MaKhachHang : number <<generated>>
--
TenDangNhap: string
MatKhau: string
HoTenKH: text
NgaySinhKH: date
SoDienThoaiKH: string
}




entity "QUANLY" #LightGreen {
*MaQuanLy: number <<genrerated>>
--
HoTenQL: text
TenDangNhap: string
MatKhau: string
NgaySinh: date
DiaChi: string
SoDienThoai: string
}




SANPHAM }o--|| DANHMUC
SANPHAM }o.."GIOHANG-HOADON"
KHACHHANG ||.."GIOHANG-HOADON"
DANHMUC }o--|| KHUYENMAI
@enduml
